[UCSC-83] Interstitial block patterns
ucsc/ucsc-2022 pull request #218
Opened 2023-05-29 16:35 UTC by bjcooper

Adds block patterns for three types of interstitial:
- Interstitial (centered, no background, colored heading, large body text)
- Intertistial, left aligned (left-aligned, no background)
- Interstitial with background (centered, green background)

2023-05-31 15:09 UTC, Vinsanity requested changes

2023-05-31 15:09 UTC, Vinsanity commented on patterns/interstitial-with-background.php
> +<?php
Let's try to move this to a group style and apply the background that way. We want to try to greater one pattern to rule them all here. and having the group class added (see above) will help achieve this. It is totally fine to have custom styles added to this to lock it down.

2023-06-01 19:38 UTC, bjcooper commented
OK, @Vinsanity , I paired this down to just a good starting point based on our chat and I'm ready for you to review the changes again. Thank you!

2023-06-01 20:32 UTC, Vinsanity approved these changes
🟢  Great! Nice work here @bjcooper

2023-06-06 21:28 UTC, merged