[UCSC-134] Sidebar Menu
ucsc/ucsc-2022 pull request #268
Opened 2023-09-20 19:18 UTC by bjcooper

## What does this do/fix?

Adds styles and JS behaviors for the "Content with left navigation" block pattern.

## QA

Links to relevant issues
- [UCSC-134](https://example.com)](https://moderntribe.atlassian.net/browse/UCSC-134)

Screenshots/video:
![image](https://github.com/ucsc/ucsc-2022/assets/6012180/7fd0617b-17fb-4aae-aa42-666de6d3667d)

2023-10-02 13:54 UTC, bjcooper commented
_bump_ @Vinsanity

2023-10-04 23:01 UTC, Vinsanity requested changes
@bjcooper concept looks great! nice work. Just some small items to address and clean up and one or two items to review for next time. Let me know if you have any questions on those.

2023-10-04 23:01 UTC, Vinsanity commented on src/scss/block-patterns/_sidebar-with-navigation.scss
> +			> .wp-block-navigation-item {
the nesting here is getting quite deep which will create an excessively long string. Can we move this out of here and add classes to blocks to reduce that?

2023-10-10 16:52 UTC, bjcooper commented on patterns/sidebar-with-navigation.php
> +<!-- wp:navigation {"ref":1857,"textColor":"ucsc-royal-blue","overlayMenu":"never","overlayTextColor":"ucsc-royal-blue","maxNestingLevel":1,"layout":{"type":"flex","orientation":"vertical","justifyCo
Thanks, Vinny. The `ref` entry has been removed.

2023-10-10 16:53 UTC, bjcooper commented on src/js/block-patterns/sidebar-with-navigation.js
> +const bindEvents = () => {
Oh, nice! I've used that in SQ1 projects before but didn't know we had it available in this project.

2023-10-10 16:53 UTC, bjcooper commented on src/js/block-patterns/sidebar-with-navigation.js
> +			.querySelectorAll( c.submenuSelector + ' ' + c.submenuSelector )
Done.

2023-10-10 17:11 UTC, bjcooper commented on src/js/block-patterns/sidebar-with-navigation.js
> +let c = {};
I renamed blocks to use the elements convention. The other bits are not cached element references, just selector strings and CSS classes I didn't want to hardcode as magic strings through the script. Those, I just flatly declare now in order to be less confusing.

2023-10-16 15:49 UTC, Vinsanity approved these changes
🟢

2023-10-16 15:50 UTC, merged